
INSERT INTO public.seo_pages
  (slug, page_type, city_slug, category_slug, schema_type, is_published,
   title_en, title_he, title_ru, meta_en, meta_he, meta_ru, h1_en, h1_he, h1_ru,
   content_en, content_he, content_ru, faq, keywords)
SELECT
  v.slug, v.page_type, v.city_slug, v.category_slug, v.schema_type, v.is_published,
  v.title_en, v.title_he, v.title_ru, v.meta_en, v.meta_he, v.meta_ru, v.h1_en, v.h1_he, v.h1_ru,
  v.content_en, v.content_he, v.content_ru,
  '[
    {"question_en":"How does 4You.AI work?","question_he":"איך 4You.AI עובד?","question_ru":"Как работает 4You.AI?","answer_en":"A customer posts a task, taskers send offers, the customer chooses a tasker, and the order is completed after the work is done.","answer_he":"הלקוח מפרסם משימה, נותני השירות שולחים הצעות, הלקוח בוחר נותן שירות וההזמנה מסתיימת לאחר ביצוע העבודה.","answer_ru":"Клиент публикует задачу, исполнители отправляют предложения, клиент выбирает подходящего исполнителя и завершает заказ после выполнения."},
    {"question_en":"How does payment work?","question_he":"איך מתבצע התשלום?","question_ru":"Как проходит оплата?","answer_en":"Payment is processed through the platform. Funds are held until task completion or dispute resolution.","answer_he":"התשלום מתבצע דרך הפלטפורמה. הכסף מוחזק עד לסיום המשימה או פתרון מחלוקת.","answer_ru":"Оплата проходит через платформу. Средства удерживаются до завершения задачи или разрешения спорной ситуации."},
    {"question_en":"Can I choose the tasker myself?","question_he":"אפשר לבחור את נותן השירות לבד?","question_ru":"Можно ли выбрать исполнителя самому?","answer_en":"Yes, the customer compares offers, profiles, experience, and reviews before choosing a tasker.","answer_he":"כן, הלקוח משווה הצעות, פרופילים, ניסיון וביקורות ובוחר את המתאים ביותר.","answer_ru":"Да, клиент сравнивает предложения, профили, опыт и отзывы, а затем выбирает подходящего исполнителя."}
  ]'::jsonb,
  v.keywords
FROM (VALUES
  ('kiryat-bialik','city',NULL::text,NULL::text,'LocalBusiness',true,
    'Find taskers in Kiryat Bialik | Flow4You.AI',
    'מצא נותני שירות בקריית ביאליק | Flow4You.AI',
    'Найти исполнителя в Кирьят-Бялик | Flow4You.AI',
    'Local services in Kiryat Bialik: cleaning, repairs, delivery, moving help, and home tasks.',
    'שירותים בקריית ביאליק: ניקיון, תיקונים, משלוחים, מעבר דירה ועזרה בבית.',
    'Услуги в Кирьят-Бялик: уборка, ремонт, доставка, переезд и помощь по дому.',
    'Taskers for everyday tasks in Kiryat Bialik',
    'נותני שירות בקריית ביאליק',
    'Исполнители для задач в Кирьят-Бялик',
    'Kiryat Bialik is a residential city in the Krayot area north of Haifa. On Flow4You.AI locals look for help with apartments and private houses, garden upkeep, small repairs, moving between neighborhoods, and home cleaning. This city page links to the main categories: cleaning, small repairs, delivery, moving help, and handyman tasks. A customer posts a task, adds neighborhood, timing, budget, and requirements; taskers send offers and the customer chooses the best match. The page acts as useful navigation with city-service links, a process explanation, FAQ, safety section, and a clear call to action. We do not invent reviews, order counts, or guarantees — only real product mechanics: profiles, offers, in-app chat, reviews, protected payment flow, and dispute support.',
    'קריית ביאליק היא עיר מגורים בקריות, צפונית לחיפה. ב-Flow4You.AI התושבים מחפשים עזרה בדירות ובבתים פרטיים, טיפול בגינה, תיקונים קטנים, מעבר בין שכונות וניקיון הבית. עמוד העיר מקשר לקטגוריות המרכזיות: ניקיון, תיקונים קטנים, משלוחים, עזרה במעבר דירה והנדימן. הלקוח מפרסם משימה, מוסיף שכונה, זמן, תקציב ודרישות; נותני השירות שולחים הצעות והלקוח בוחר את המתאים ביותר. העמוד משמש ניווט שימושי עם קישורים לשירותים בעיר, הסבר תהליך, שאלות נפוצות, בטיחות וקריאה לפעולה. איננו ממציאים ביקורות, מספרי הזמנות או הבטחות — רק מנגנוני מוצר אמיתיים: פרופילים, הצעות, צ׳אט באפליקציה, ביקורות, תשלום מוגן ותמיכה במחלוקות.',
    'Кирьят-Бялик — жилой город в районе Крайот к северу от Хайфы. На Flow4You.AI местные жители ищут помощь с квартирами и частными домами, уходом за садом, мелким ремонтом, переездами между районами и уборкой дома. Страница города ведёт к основным категориям: уборка, мелкий ремонт, доставка, переезд и мастер на час. Клиент создаёт задачу, указывает район, сроки, бюджет и требования; исполнители присылают предложения, а клиент выбирает подходящего. Страница работает как удобная навигация с ссылками на услуги в городе, объяснением процесса, FAQ, блоком безопасности и понятным призывом к действию. Мы не придумываем отзывы, число заказов или гарантии — только реальные механики: профили, предложения, чат, отзывы, защищённая оплата и поддержка споров.',
    ARRAY['city','kiryat-bialik','Israel','4You.AI']),

  ('kiryat-bialik/cleaning','city_category','kiryat-bialik','cleaning','Service',true,
    'Cleaning in Kiryat Bialik | Flow4You.AI',
    'ניקיון בקריית ביאליק | Flow4You.AI',
    'Уборка в Кирьят-Бялик | Flow4You.AI',
    'Cleaning in Kiryat Bialik: post a task and receive offers from local taskers.',
    'ניקיון בקריית ביאליק: פרסם משימה וקבל הצעות מנותני שירות מקומיים.',
    'Уборка в Кирьят-Бялик: разместите задачу и получите предложения от исполнителей.',
    'Cleaning in Kiryat Bialik','ניקיון בקריית ביאליק','Уборка в Кирьят-Бялик',
    'Cleaning in Kiryat Bialik covers apartments, private houses common in the Krayot, post-renovation cleaning, and move-in / move-out cleaning. On Flow4You.AI the customer posts a task with neighborhood, scope of work, exact area, preferred date, and photos when needed. Taskers send offers; the customer compares price, profile, experience, and reviews. Payment goes through a protected flow — funds are held until completion or dispute resolution. The page is useful navigation, not a thin SEO placeholder.',
    'ניקיון בקריית ביאליק כולל דירות, בתים פרטיים נפוצים בקריות, ניקיון אחרי שיפוץ והכנת דירה לכניסה או יציאה. ב-Flow4You.AI הלקוח מפרסם משימה עם שכונה, היקף עבודה, שטח מדויק, תאריך רצוי ותמונות במידת הצורך. נותני השירות שולחים הצעות; הלקוח משווה מחיר, פרופיל, ניסיון וביקורות. התשלום מתבצע בתהליך מוגן — הכסף מוחזק עד לסיום או פתרון מחלוקת.',
    'Уборка в Кирьят-Бялик охватывает квартиры, частные дома, типичные для Крайот, уборку после ремонта и подготовку жилья к заселению или выезду. На Flow4You.AI клиент публикует задачу с указанием района, объёма, точной площади, желаемой даты и фото при необходимости. Исполнители присылают предложения; клиент сравнивает цену, профиль, опыт и отзывы. Оплата идёт через защищённый процесс — средства удерживаются до завершения или разрешения спора.',
    ARRAY['city_category','kiryat-bialik','cleaning','Israel','4You.AI']),

  ('kiryat-bialik/repair','city_category','kiryat-bialik','repair','Service',true,
    'Small repairs in Kiryat Bialik | Flow4You.AI',
    'תיקונים קטנים בקריית ביאליק | Flow4You.AI',
    'Мелкий ремонт в Кирьят-Бялик | Flow4You.AI',
    'Small repairs in Kiryat Bialik: post a task and receive offers from local taskers.',
    'תיקונים קטנים בקריית ביאליק: פרסם משימה וקבל הצעות מנותני שירות מקומיים.',
    'Мелкий ремонт в Кирьят-Бялик: разместите задачу и получите предложения от исполнителей.',
    'Small repairs in Kiryat Bialik','תיקונים קטנים בקריית ביאליק','Мелкий ремонт в Кирьят-Бялик',
    'Small repairs in Kiryat Bialik include electrics, plumbing, doors and locks, blinds, and similar household fixes typical for Krayot apartments and houses. The customer posts a task with details and photos; taskers send offers; the customer picks the right one. Payment is protected and released after the work is done.',
    'תיקונים קטנים בקריית ביאליק כוללים חשמל, אינסטלציה, דלתות ומנעולים, תריסים ותיקונים ביתיים אופייניים לדירות ולבתים בקריות. הלקוח מפרסם משימה עם פרטים ותמונות; נותני השירות שולחים הצעות; הלקוח בוחר את המתאים. התשלום מוגן ומשוחרר לאחר ביצוע העבודה.',
    'Мелкий ремонт в Кирьят-Бялик — это электрика, сантехника, двери и замки, жалюзи и другие бытовые мелочи, характерные для квартир и домов Крайот. Клиент публикует задачу с деталями и фото; исполнители присылают предложения; клиент выбирает подходящего. Оплата защищена и переводится после выполнения работ.',
    ARRAY['city_category','kiryat-bialik','repair','Israel','4You.AI']),

  ('kiryat-bialik/moving','city_category','kiryat-bialik','moving','Service',true,
    'Moving help in Kiryat Bialik | Flow4You.AI',
    'עזרה במעבר דירה בקריית ביאליק | Flow4You.AI',
    'Помощь при переезде в Кирьят-Бялик | Flow4You.AI',
    'Moving help in Kiryat Bialik: post a task and receive offers from local taskers.',
    'עזרה במעבר דירה בקריית ביאליק: פרסם משימה וקבל הצעות מנותני שירות מקומיים.',
    'Помощь при переезде в Кирьят-Бялик: разместите задачу и получите предложения от исполнителей.',
    'Moving help in Kiryat Bialik','עזרה במעבר דירה בקריית ביאליק','Помощь при переезде в Кирьят-Бялик',
    'Moving in Kiryat Bialik often means short trips inside the Krayot or to nearby Haifa: loading, transport, unloading, furniture assembly, and disposal of old items. The customer posts the inventory, floor, parking, and timing; taskers send offers and the customer chooses based on price and reviews. Payment goes through a protected flow.',
    'מעבר דירה בקריית ביאליק כולל לעיתים נסיעות קצרות בתוך הקריות או לחיפה הסמוכה: העמסה, הובלה, פריקה, הרכבת רהיטים ופינוי פריטים ישנים. הלקוח מפרסם את הרשימה, קומה, חניה וזמן; נותני השירות שולחים הצעות והלקוח בוחר לפי מחיר וביקורות. התשלום מתבצע בתהליך מוגן.',
    'Переезд в Кирьят-Бялик — это часто короткие поездки внутри Крайот или в соседнюю Хайфу: погрузка, перевозка, разгрузка, сборка мебели и вывоз старых вещей. Клиент публикует список, этаж, парковку и время; исполнители присылают предложения, клиент выбирает по цене и отзывам. Оплата идёт через защищённый процесс.',
    ARRAY['city_category','kiryat-bialik','moving','Israel','4You.AI']),

  ('kiryat-bialik/delivery','city_category','kiryat-bialik','delivery','Service',true,
    'Delivery and errands in Kiryat Bialik | Flow4You.AI',
    'משלוחים וסידורים בקריית ביאליק | Flow4You.AI',
    'Доставка и поручения в Кирьят-Бялик | Flow4You.AI',
    'Delivery and errands in Kiryat Bialik: post a task and receive offers from local taskers.',
    'משלוחים וסידורים בקריית ביאליק: פרסם משימה וקבל הצעות מנותני שירות מקומיים.',
    'Доставка и поручения в Кирьят-Бялик: разместите задачу и получите предложения от исполнителей.',
    'Delivery and errands in Kiryat Bialik','משלוחים וסידורים בקריית ביאליק','Доставка и поручения в Кирьят-Бялик',
    'Delivery and errands in Kiryat Bialik cover small parcels, groceries, documents, pharmacy runs, and quick trips inside the Krayot or to Haifa. The customer specifies pickup and drop-off addresses, item size, and timing; taskers send offers and the customer picks the best one. Payment is processed safely through the platform.',
    'משלוחים וסידורים בקריית ביאליק כוללים חבילות קטנות, קניות, מסמכים, איסוף מבית מרקחת ונסיעות קצרות בתוך הקריות או לחיפה. הלקוח מציין כתובת איסוף ומסירה, גודל הפריט וזמנים; נותני השירות שולחים הצעות והלקוח בוחר את המתאים. התשלום מתבצע באופן בטוח דרך הפלטפורמה.',
    'Доставка и поручения в Кирьят-Бялик — это небольшие посылки, продукты, документы, аптека и короткие поездки внутри Крайот или в Хайфу. Клиент указывает адреса забора и доставки, размер и сроки; исполнители присылают предложения, клиент выбирает подходящего. Оплата проходит безопасно через платформу.',
    ARRAY['city_category','kiryat-bialik','delivery','Israel','4You.AI']),

  ('kiryat-bialik/handyman','city_category','kiryat-bialik','handyman','Service',true,
    'Handyman in Kiryat Bialik | Flow4You.AI',
    'הנדימן בקריית ביאליק | Flow4You.AI',
    'Мастер на час в Кирьят-Бялик | Flow4You.AI',
    'Handyman in Kiryat Bialik: post a task and receive offers from local taskers.',
    'הנדימן בקריית ביאליק: פרסם משימה וקבל הצעות מנותני שירות מקומיים.',
    'Мастер на час в Кирьят-Бялик: разместите задачу и получите предложения от исполнителей.',
    'Handyman in Kiryat Bialik','הנדימן בקריית ביאליק','Мастер на час в Кирьят-Бялик',
    'A handyman in Kiryat Bialik can help with mounting TVs and shelves, assembling furniture, fixing leaks, replacing fixtures, and other small jobs around the home. The customer posts a task with photos and details; taskers send offers; the customer chooses by price, profile, and reviews. Payment goes through a protected flow.',
    'הנדימן בקריית ביאליק יכול לעזור בתליית טלוויזיות ומדפים, הרכבת רהיטים, תיקון נזילות, החלפת אביזרים ועבודות קטנות נוספות בבית. הלקוח מפרסם משימה עם תמונות ופרטים; נותני השירות שולחים הצעות; הלקוח בוחר לפי מחיר, פרופיל וביקורות. התשלום מתבצע בתהליך מוגן.',
    'Мастер на час в Кирьят-Бялик поможет с установкой телевизоров и полок, сборкой мебели, устранением протечек, заменой фурнитуры и другими мелкими работами по дому. Клиент публикует задачу с фото и деталями; исполнители присылают предложения; клиент выбирает по цене, профилю и отзывам. Оплата идёт через защищённый процесс.',
    ARRAY['city_category','kiryat-bialik','handyman','Israel','4You.AI'])
) AS v(slug, page_type, city_slug, category_slug, schema_type, is_published,
       title_en, title_he, title_ru, meta_en, meta_he, meta_ru, h1_en, h1_he, h1_ru,
       content_en, content_he, content_ru, keywords)
ON CONFLICT (slug) DO NOTHING;
